import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import react from "ultracite/oxlint/react";

export default defineConfig({
  extends: [core, react],
  // Tool configs are validated by Ultracite Doctor and their own CLIs. Type-aware
  // lint cannot resolve Oxfmt's config-only type surface through the repo projects.
  ignorePatterns: [...core.ignorePatterns, "oxlint.config.ts", "oxfmt.config.ts"],
  options: {
    typeAware: true,
  },
  overrides: [
    {
      files: ["packages/renderers/src/row-document-renderable.ts"],
      rules: {
        "no-underscore-dangle": "off",
      },
    },
  ],
  rules: {
    // Rule gate: rules with findings at the migration baseline are disabled.
    // All other Ultracite rules remain enabled, so any newly failing rule blocks the gate.
    "accessor-pairs": "off",
    complexity: "off",
    "default-case": "off",
    eqeqeq: "off",
    "func-names": "off",
    "no-bitwise": "off",
    "no-duplicate-imports": ["error", { allowSeparateTypeImports: true }],
    "no-empty": "off",
    "no-empty-function": "off",
    "no-eq-null": "off",
    "no-lonely-if": "off",
    "no-negated-condition": "off",
    "no-nested-ternary": "off",
    "no-promise-executor-return": "off",
    "prefer-destructuring": "off",
    "prefer-named-capture-group": "off",
    "import/no-duplicates": "off",
    "promise/avoid-new": "off",
    "promise/param-names": "off",
    "promise/prefer-await-to-callbacks": "off",
    "promise/prefer-await-to-then": "off",
    "react/hook-use-state": "off",
    "react/jsx-handler-names": "off",
    "react/jsx-no-useless-fragment": "off",
    "typescript/array-type": "off",
    "typescript/await-thenable": "off",
    "typescript/ban-types": "off",
    "typescript/consistent-return": "off",
    "typescript/consistent-type-definitions": "off",
    "typescript/dot-notation": "off",
    "typescript/no-base-to-string": "off",
    "typescript/no-deprecated": "off",
    "typescript/no-empty-object-type": "off",
    "typescript/no-explicit-any": "off",
    "typescript/no-invalid-void-type": "off",
    "typescript/no-misused-promises": "off",
    "typescript/no-redundant-type-constituents": "off",
    "typescript/no-unnecessary-type-parameters": "off",
    "typescript/no-unsafe-argument": "off",
    "typescript/no-unsafe-assignment": "off",
    "typescript/no-unsafe-call": "off",
    "typescript/no-unsafe-member-access": "off",
    "typescript/no-unsafe-return": "off",
    "typescript/non-nullable-type-assertion-style": "off",
    "typescript/only-throw-error": "off",
    "typescript/parameter-properties": "off",
    "typescript/prefer-nullish-coalescing": "off",
    "typescript/prefer-readonly": "off",
    "typescript/prefer-regexp-exec": "off",
    "typescript/restrict-template-expressions": "off",
    "typescript/return-await": "off",
    "typescript/switch-exhaustiveness-check": "off",
    "typescript/unbound-method": "off",
    "unicorn/catch-error-name": "off",
    "unicorn/consistent-existence-index-check": "off",
    "unicorn/import-style": "off",
    "unicorn/no-array-for-each": "off",
    "unicorn/no-array-method-this-argument": "off",
    "unicorn/no-array-sort": "off",
    "unicorn/no-immediate-mutation": "off",
    "unicorn/no-negated-condition": "off",
    "unicorn/no-nested-ternary": "off",
    "unicorn/no-useless-switch-case": "off",
    "unicorn/prefer-at": "off",
    "unicorn/prefer-code-point": "off",
    "unicorn/prefer-export-from": "off",
    "unicorn/prefer-number-coercion": "off",
    "unicorn/prefer-number-properties": "off",
    "unicorn/prefer-regexp-test": "off",
    "unicorn/prefer-single-call": "off",
    "unicorn/prefer-spread": "off",
    "unicorn/prefer-type-error": "off",
    "unicorn/switch-case-braces": "off",
    // Tooee does not use React Compiler, so compiler-adoption guidance is not applicable.
    "react/react-compiler": "off",
    "jsx-a11y/alt-text": "off",
    "jsx-a11y/anchor-ambiguous-text": "off",
    "jsx-a11y/anchor-has-content": "off",
    "jsx-a11y/anchor-is-valid": "off",
    "jsx-a11y/aria-activedescendant-has-tabindex": "off",
    "jsx-a11y/aria-props": "off",
    "jsx-a11y/aria-proptypes": "off",
    "jsx-a11y/aria-role": "off",
    "jsx-a11y/aria-unsupported-elements": "off",
    "jsx-a11y/autocomplete-valid": "off",
    "jsx-a11y/click-events-have-key-events": "off",
    "jsx-a11y/control-has-associated-label": "off",
    "jsx-a11y/heading-has-content": "off",
    "jsx-a11y/html-has-lang": "off",
    "jsx-a11y/iframe-has-title": "off",
    "jsx-a11y/img-redundant-alt": "off",
    "jsx-a11y/interactive-supports-focus": "off",
    "jsx-a11y/label-has-associated-control": "off",
    "jsx-a11y/lang": "off",
    "jsx-a11y/media-has-caption": "off",
    "jsx-a11y/mouse-events-have-key-events": "off",
    "jsx-a11y/no-access-key": "off",
    "jsx-a11y/no-aria-hidden-on-focusable": "off",
    "jsx-a11y/no-autofocus": "off",
    "jsx-a11y/no-distracting-elements": "off",
    "jsx-a11y/no-interactive-element-to-noninteractive-role": "off",
    "jsx-a11y/no-noninteractive-element-interactions": "off",
    "jsx-a11y/no-noninteractive-element-to-interactive-role": "off",
    "jsx-a11y/no-noninteractive-tabindex": "off",
    "jsx-a11y/no-redundant-roles": "off",
    "jsx-a11y/no-static-element-interactions": "off",
    "jsx-a11y/prefer-tag-over-role": "off",
    "jsx-a11y/role-has-required-aria-props": "off",
    "jsx-a11y/role-supports-aria-props": "off",
    "jsx-a11y/scope": "off",
    "jsx-a11y/tabindex-no-positive": "off",
  },
});
