/**
 * Static files the sync script writes next to the vendored termcn source:
 * shims for the specifiers in SHIMMED_SPECIFIERS, a tsconfig so Bun compiles
 * the demos with the OpenTUI JSX runtime, and the provenance record.
 */

export const TERMCN_REPO_URL = "https://github.com/shadcn-labs/termcn.git";

/** Pinned termcn commit (2026-10-07, "feat: add mdxcn to nav"). */
export const TERMCN_COMMIT = "fd28627bb340f5eaa1a5824d47db6373a739d95a";

/** Source roots copied in full, relative to termcn's `apps/web/`. */
export const SEED_DIRECTORIES = ["registry/bases/opentui", "examples/opentui"] as const;

export const INK_SHIM = `// Generated by examples/termcn/scripts/sync-vendor.ts.
// termcn's shared Ink hooks import two Ink hooks. Outside an Ink app they
// would read Ink's default context values, which these stubs reproduce.
export const useIsScreenReaderEnabled = (): boolean => false;

export const useStdout = () => ({
  stdout: process.stdout,
  write: (data: string): void => {
    process.stdout.write(data);
  },
});
`;

export const BASES_SHIM = `// Generated by examples/termcn/scripts/sync-vendor.ts.
// termcn's registry/bases.ts imports website icons. The OpenTUI theme index
// only needs the base names.
export const BASE_NAMES = ["ink", "opentui"] as const;

export type BaseName = (typeof BASE_NAMES)[number];
`;

export const VENDOR_TSCONFIG = `${JSON.stringify(
  {
    compilerOptions: {
      jsx: "react-jsx",
      jsxImportSource: "@opentui/react",
      module: "ESNext",
      moduleResolution: "bundler",
      target: "ESNext",
    },
  },
  null,
  2
)}\n`;

export interface VendorManifest {
  repository: string;
  commit: string;
  syncedAt: string;
  files: number;
  demos: number;
}
